id: influx-listen
namespace: io.kestra.tests

triggers:
  - id: watch
    type: io.kestra.plugin.influxdb.FluxTrigger
    connection:
      url: "http://localhost:8086"
      token: "my-token"
    org: "my-org"
    query: |
      from(bucket: "test-bucket")
        |> range(start: -1h)
        |> limit(n: 10)
    interval: PT10S

tasks:
  - id: each
    type: io.kestra.plugin.core.flow.ForEach
    values: "{{ trigger.rows }}"
    tasks:
      - id: return
        type: io.kestra.plugin.core.debug.Return
        format: "{{ json(taskrun.value) }}"
